#!/bin/bash

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝


killall polybar
~/.config/polybar/scripts/polybarstart &
xrdb -merge ~/.Xresources
killall sxhkd
sxhkd -c ~/.config/sxhkd/sxhkdrc &
~/.scripts/bindings/touchpad &

~/.scripts/fehbg &
~/.config/picom/scripts/picomstart
libinput-gestures-setup start

wmname LG3D

##bspwm configuration

bspc monitor -d 1 2 3 4 8 9 10


bspc config focus_follows_pointer 	true
bspc config border_width		5
bspc config window_gap			35

