#!/bin/bash

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝


killall polybar
~/.config/polybar/scripts/polybarstart &
xrdb -merge ~/.Xresources
killall sxhkd
sxhkd -c ~/.config/sxhkd/sxhkdrc &
~/.scripts/bindings/touchpad &
~/.scripts/bindings/keyboard &

~/.scripts/fehbg &
~/.config/picom/scripts/picomstart
libinput-gestures-setup start

# sets the window manager name to allow jetbrains functionality
wmname LG3D

##bspwm configuration

bspc monitor -d 1 2 3 4 5 8 9 10


bspc config focus_follows_pointer 	true
bspc config border_width		0
bspc config window_gap			35

