#!/bin/bash

SIZE=40

# while [ true ];
# do

	FULLNAME=$(mpc current)
	NAME=$(echo $FULLNAME | cut -c 1-$SIZE | fribidi)

	if [ ${#FULLNAME} -gt $SIZE ];
	then
		NAME+="..."
	fi

	NAME+=" | "

	if [ $(mpc | grep "\[p" | cut -c 2-5) == "play" ]; 
	then 
		echo "  "$NAME" "
	else 
		echo "  "$NAME" "
	fi

	# mpc idle player;
# done
