#!/bin/bash

SIZE=42

#if [ $STATUS=="Stopped" ];
if [ $(mpc | grep "\[p" | cut -c 2-5) == "play" ];
then
	NAME=$(~/.scripts/polybar/module_mpc)
	echo "$NAME"
else
	STATUS=$(playerctl status)
	FULLNAME=$(playerctl metadata artist)" - "
	FULLNAME+=$(playerctl metadata title)" "

	#FULLNAME=$(mpc current)

	NAME=$(echo "$FULLNAME" | cut -c 1-$SIZE | fribidi)

	if [ ${#FULLNAME} != 0 ];
	then

		if [ ${#FULLNAME} -gt $SIZE ];
		then
			NAME+="..."

		# NAME+=" || "$(playerctl status)
		fi

		if [ $STATUS == "Playing" ]
		#if [ "Playing" == "Playing" ]
		#if [ $(mpc | grep "\[" | cut -c 2-5) == "play" ]; 
		then
			#NAME+=" | "	# alternative
			#NAME+=" | "	# circular
			NAME+="|  "
		else
			#NAME+=" | "	# alternative
			#NAME+=" | "	# circular
			NAME+="|  "
		fi

		echo "  ""$NAME"
	fi
fi
