#!/bin/bash

if bluetoothctl show | grep -q 'Powered: yes' ; then
	bluetoothctl power off
else
	bluetoothctl power on
	#bluetoothctl connect FC:A8:9A:81:47:FC
	#bluetoothctl connect 74:5C:4B:2D:67:AC
fi
